{
 "title": "HTTP Metric Otel",
 "description": "HTTP Metric based Otel metrics",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_sum,net_host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate (Non 5xx)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code!~\"5..\"}[$__range]))/sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range]))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code=~\"2..|3..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code=~\"4..\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code=~\"5..\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50/P90/P99 Request Duration Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Request Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range])) by (http_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(http_server_duration_milliseconds_sum{net_host_name=\"${host}\"}[$__range]))by(http_route)/(sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range]))by(http_route)>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "HTTP Workload",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range])) by(http_route) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\",http_status_code!~\"5..\"}[$__range])) by(http_route)/sum(rate(http_server_duration_milliseconds_count{net_host_name=\"${host}\"}[$__range])) by(http_route) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(http_server_duration_milliseconds_bucket{net_host_name=\"${host}\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}